### ISSUE TITLE
There are too many labels created using this time range approach

### ISSUE THREAD

**Issue by tonyxu-io** [Allen1212/trace-ark-trades#1]
They way you create the labels not just create one label, but it actually created lots of labels in each unit within the time range. When you zoom out to 1Y you may not notice, but it's obvious when you zoom in to 1M or days.

**Comment by Allen1212** [comment]
Thanks for reporting this issue. I use a timestamp function instead of a time range. This issue is fixed now.

**Comment by tonyxu-io** [comment]
Thanks for the rapid fix. Appreciate it! By the way this project is super helpful.

**Comment by Allen1212** [comment]
Thank you. Enjoy your investment!
