### ISSUE TITLE
Ark notification issue

### ISSUE THREAD

**Issue by martinyan** [Allen1212/trace-ark-trades#2]
Great code btw...the biggest issue is actually the notification from Ark doesn't contain all their trade.
Its been discovered by many who followed Ark's trades that the only way to correctly track their buy/sell is to take snapshot of their portfolio and compare them on a daily basis...just FYI.

**Comment by Allen1212** [comment]
Hey martinyan,

Thanks for your comment! I found this issue when I compared the share changes between the ARK's holding report and the daily trade logs. I don't know why there are some differences. Maybe it's a good idea to compare the portfolio with the previous day. I may do some research on the Christmas break and decide whether we need to do it like this. If you have any thoughts, please let me know.

Best Regards,
Allen

**Comment by martinyan** [comment]
I am indeed working on a script that compare their portfolio to get the buy/sell log...same here, its just too busy before the year end 👍

**Comment by Allen1212** [comment]
Good! Wish you a merry Christmas🎊

**Comment by goodman-capu** [comment]
I believe alien tomato is already using the method to compare daily holdings and calculate transactions. [Reference](https://www.youtube.com/watch?v=nbq79rz4HzY)
Any plans to follow up on that?

**Comment by Allen1212** [comment]
@goodman-capu Thanks for checking out this project! Yes, I plan to fetch and compare the trading logs from daily holdings in the next version. But I still have some questions about ARK's daily holdings and have sent my issues to ARK. I hope they can reply to my questions soon.

**Comment by martinyan** [comment]
Hi Guy, I believe how Alien Tomato did it is with the Finhub.io API cos he is quoting referring to it at the bottom of his page.  I took a look at the api and believe it did provide such ETF composition function.  I didn’t have a chance to look into the details yet though.

**Comment by Allen1212** [comment]
@martinyan @goodman-capu Hey guys, I start to track ETFs' daily holdings instead of collecting trading records from email. Thanks for submitting this issue. Hope this project can help your investment!

**Comment by goodman-capu** [comment]
> Hi Guy, I believe how Alien Tomato did it is with the Finhub.io API cos he is quoting referring to it at the bottom of his page. I took a look at the api and believe it did provide such ETF composition function. I didn’t have a chance to look into the details yet though.
> […](#)
> Sent from my iPhone
> On 9 Jan 2021, at 1:40 AM, Allen1212 ***@***.***> wrote: ﻿ @goodman-capu Thanks for checking out this project! Yes, I plan to fetch and compare the trading logs from daily holdings in the next version. But I still have some questions about ARK's daily holdings and have sent my issues to ARK. I hope they can reply to my questions soon. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

In his YouTube video, he clearly stated that the transactions are calculated from daily holdings change csv from ARK's website. I think finnhub is only for the candle data.

BTW I used finnhub before, and their API on company info and etf components are extremely inaccurate and outdated. They just seem to never update the info. Finnhub shouldn't be the source of truth :(
