### ISSUE TITLE
Add support for `CTRU`

### ISSUE THREAD

**Issue by MichaelDeBoey** [Allen1212/trace-ark-trades#6]
https://ark-funds.com/funds/ctru

**Comment by MichaelDeBoey** [comment]
@Allen1212 
- https://ark-funds.com/wp-content/uploads/funds-etf-pdf/ARK_TRANSPARENCY_ETF_CTRU_HOLDINGS.pdf
- https://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_TRANSPARENCY_ETF_CTRU_HOLDINGS.csv

**Comment by Allen1212** [comment]
> @Allen1212
> 
> * https://ark-funds.com/wp-content/uploads/funds-etf-pdf/ARK_TRANSPARENCY_ETF_CTRU_HOLDINGS.pdf
> * https://ark-funds.com/wp-content/uploads/funds-etf-csv/ARK_TRANSPARENCY_ETF_CTRU_HOLDINGS.csv

**Comment by Allen1212** [comment]
Hey, Michaël! Sorry, I found the CTRU is an index ETF. I will not track it currently but I am thank you for reminding me and following this project.
